
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: test
      description: created to do basic test
      columns:
        - name: id
          tests:
            - not_null
            - unique
        - name: name
          description: contains name
          tests:
            - not_null